port to ESM modules
ankostis/gnome-shell-quick-lang-switch pull request #13
Opened 2023-09-19 11:31 UTC by thankjura

2023-09-19 13:52 UTC, ankostis requested changes

2023-09-19 13:52 UTC, ankostis commented on metadata.json
> +  "shell-version": ["45"],
Would that continue to work also for older versions?

2023-09-19 13:52 UTC, ankostis commented on extension.js
> -const KeyboardManager = imports.misc.keyboardManager;
Is that a bug to fetch KM that early?
Maybe a separate commit with an appropriate message explaining the bug fix is warranted?

2023-09-19 13:52 UTC, ankostis commented on extension.js
> +        const nextSource = sources[ni];
Ouch!@
That means i haven't tested it, yet :-/

2023-09-19 14:06 UTC, thankjura commented on extension.js
> -const KeyboardManager = imports.misc.keyboardManager;
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

Old imports not working on gnome-45

2023-09-19 14:11 UTC, thankjura commented on metadata.json
> +  "shell-version": ["45"],
No. Only for gnome>=45.
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version
>The good news is that e.g.o supports multi versioning - you can still submit multiple packages with different shell versions.

2023-09-19 14:21 UTC, ankostis commented on metadata.json
> +  "shell-version": ["45"],
That means that we need an additional separate branch to follow 45.
Could we delay transitioning to ESM, and still provide for 45 compatibility with the old code?

2023-09-19 14:29 UTC, thankjura commented on metadata.json
> +  "shell-version": ["45"],
>GNOME Shell 45 moved to ESM (ECMAScript modules). That means you [MUST](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm) use the standard import declaration instead of relying on the previous imports.* approach.

[Gnome 45 break extensions backward compatibility](https://www.reddit.com/r/linux/comments/169r5o8/the_upcoming_gnome_45_will_break_extensions/)

2023-11-11 12:12 UTC, aloise approved these changes

2023-11-12 21:06 UTC, merged