Update README.md
ankostis/gnome-shell-quick-lang-switch pull request #18
Opened 2024-10-14 16:28 UTC by AHSaqib

Updated the manual to enhance the guidelines.

2025-09-24 09:04 UTC, ankostis requested changes
Thank you for you enhancements, i understood your pain points and you fixed it.

I have submitted some feedback (re-writing  your commit is preferable but optional).

2025-09-24 09:04 UTC, ankostis commented on README.md
> +Here’s a polished version of your installation instructions:
I guess the next 4 lines are not meant to end up in the readme, correct?

2025-09-24 09:04 UTC, ankostis commented on README.md
> +Sometimes, the developer may be unavailable, and a new GNOME version may be released. In such cases, you may need to follow the manual installation steps and make some adjustments.
Move this case below (see my next comment)

2025-09-24 09:04 UTC, ankostis commented on README.md
> +This version is compatible with GNOME versions 45-47. If a new version is released, you will need to update the `metadata.json` file to include the new version number. For example, if the next versio
Omit the compatibility statement which has already become outdated, and begin the sentence:

```md
In case a new version is released and the developer is unresponsive, you will need to update **your** `metadata.json` file ...
```

2025-09-24 09:04 UTC, ankostis commented on README.md
> +### Additional Changes
More accurate title would be: `## Bump locally Gnome-version compatibility` or something.

2025-09-24 09:04 UTC, ankostis commented on README.md
> +Add a comma after "47" and include "48":
Make it: `... and append your Gnome's version into this file:`

2025-09-24 09:04 UTC, ankostis commented on README.md
> +### 14 Oct 2024, v12: +shell-v47
Leave that out, the "Changes" section is taken care by releases.

2025-09-24 09:04 UTC, ankostis commented on README.md
> +
Simply remove the bullet character in the initial text;  isn't it better to have READMEs fit in 90-ish width lines, in case we read them from within constrained terminals?

2025-09-24 09:04 UTC, ankostis commented on README.md
> +"shell-version": ["46", "47", "48"],
```
 shell-version": ["46", "47", ..., "<your Gnome_version>"],
```

2025-09-24 09:48 UTC, AHSaqib commented
@ankostis Honestly, I am not using this extension at the moment, and I am not familiar with GitHub’s merge/commit system.  
I think I messed things up while trying AI-generated edits.  

It would be best if you could adjust as you think it should be.  
Thank you for understanding.

2025-09-25 13:08 UTC, ankostis commented
Merged re-written as 143d409.

2025-09-25 13:08 UTC, closed without merging